In [1]:
import cv2
import random
import numpy
import itertools
import pandas

ImgSource = cv2.imread("smallgray.png",1)               # Img reading as gray scale (0)
print(ImgSource)

ImgNew = []                                             # Img creation as gray scale

for i in range(64):
    ImgNew.append([])
    for j in range(64):
        ImgNew[i].append(random.randrange(255))

ImgNew = numpy.asarray(ImgNew)
print(ImgNew)
cv2.imwrite("NewGen.png",ImgNew)

ImgNew2 = []

for k in range(3):
    ImgNew2.append([])
    for l in range(64):
        ImgNew2[k].append(random.randrange(255))

for m in range(len(ImgNew2)):
    ImgFinal = numpy.asarray([x for item in ImgNew2[m] for x in itertools.repeat(item, 64)])

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]
[[237 253 130 ..., 136 105 250]
 [127  95 195 ..., 199 245 195]
 [234  86  41 ..., 136 131 225]
 ..., 
 [205  37  48 ..., 124  39  25]
 [ 80  96  24 ..., 126 236  98]
 [ 33  99 244 ..., 210 244  29]]


In [2]:
ImgFinal

array([187, 187, 187, ..., 123, 123, 123])